/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        ink: "var(--color-ink)",
        body: "var(--color-body)",
        mute: "var(--color-mute)",
        hairline: "var(--color-hairline)",
        "hairline-strong": "var(--color-hairline-strong)",
        canvas: "var(--color-canvas)",
        "canvas-soft": "var(--color-canvas-soft)",
        "canvas-soft-2": "var(--color-canvas-soft-2)",
        link: "var(--color-link)",
        "link-deep": "var(--color-link-deep)",
        "link-bg-soft": "var(--color-link-bg-soft)",
        success: "var(--color-success)",
        error: "var(--color-error)",
        "error-soft": "var(--color-error-soft)",
        "error-deep": "var(--color-error-deep)",
        warning: "var(--color-warning)",
        "warning-soft": "var(--color-warning-soft)",
        "warning-deep": "var(--color-warning-deep)",
        violet: "var(--color-violet)",
        "violet-soft": "var(--color-violet-soft)",
        "violet-deep": "var(--color-violet-deep)",
        cyan: "var(--color-cyan)",
        "cyan-soft": "var(--color-cyan-soft)",
        "cyan-deep": "var(--color-cyan-deep)",
        "highlight-pink": "var(--color-highlight-pink)",
        "highlight-magenta": "var(--color-highlight-magenta)",
        "gradient-develop-start": "var(--color-gradient-develop-start)",
        "gradient-develop-end": "var(--color-gradient-develop-end)",
        "gradient-preview-start": "var(--color-gradient-preview-start)",
        "gradient-preview-end": "var(--color-gradient-preview-end)",
        "gradient-ship-start": "var(--color-gradient-ship-start)",
        "gradient-ship-end": "var(--color-gradient-ship-end)"
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['Geist Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'monospace'],
      },
      boxShadow: {
        'level-1': 'var(--shadow-level-1)',
        'level-2': 'var(--shadow-level-2)',
        'level-3': 'var(--shadow-level-3)',
        'level-4': 'var(--shadow-level-4)',
        'level-5': 'var(--shadow-level-5)',
      },
      borderRadius: {
        none: '0px',
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        'pill-sm': '64px',
        pill: '100px',
        full: '9999px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '40px',
        '3xl': '48px',
        '4xl': '64px',
        '5xl': '96px',
        '6xl': '128px',
        section: '192px',
      }
    },
  },
  plugins: [],
}
